### ISSUE TITLE
Toggle output pin not working

### ISSUE THREAD

**Issue by Thieuzor** [Justin-Pl/PCA9698#1]
Changing the function to:

`void PCA9698::togglePin(uint8_t pin)
{
	uint8_t portNum = pin / 8;
    uint8_t rest = pin % 8;
    if (portNum < sizeof(_outputPort)) {
        _outputPort[portNum] ^= 1 << rest;
    }
}`

makes sure toggling is working.

**Comment by Justin-Pl** [comment]
I will fix this and some other Bugs I spotted tomorow. Its a little while ago i coded this library and some functions must be rewritten

**Comment by Justin-Pl** [comment]
I dont have the hardware to test but all bugs should be fixed. I pushed a new release. The index in the library registry should be published today, but you also can download the new release as .zip now. If there are some other issues please make another issue.

**Comment by Thieuzor** [comment]
Thanks! I'll test it on my hardware once I have some time.
