### ISSUE TITLE
PCA9698 configuration

### ISSUE THREAD

**Issue by Thieuzor** [Justin-Pl/PCA9698#2]
It would be great the lib would have support to change the configuration of the PCA9698 chip. So the user is able to configure it to their needs:
![image](https://user-images.githubusercontent.com/49872441/204477152-cdd1ed40-2e97-4bae-9c4f-cbc10dc16a76.png)

As standard, I would keep the default value: 0b00000010

**Comment by Justin-Pl** [comment]
I added a function to config the mode register. I will release it with all other solved issues. Perhaps today
