### ISSUE TITLE
Define PCA9698 registers in header file

### ISSUE THREAD

**Issue by Thieuzor** [Justin-Pl/PCA9698#3]
`#define PCA9698_OUTPUT_REG 0x01
#define PCA9698_CONFIGURATION_REG 0x03
#define PCA9698_INPUT_PORT0 0x00
#define PCA9698_INPUT_PORT1 0x01
#define PCA9698_INPUT_PORT2 0x02
#define PCA9698_INPUT_PORT3 0x03
#define PCA9698_INPUT_PORT4 0x04
#define PCA9698_INPUT_PORT0_AUTO_INCREMENT 0x80
#define PCA9698_OUTPUT_PORT0 0x08
#define PCA9698_OUTPUT_PORT1 0x09
#define PCA9698_OUTPUT_PORT2 0x0A
#define PCA9698_OUTPUT_PORT3 0x0B
#define PCA9698_OUTPUT_PORT4 0x0C
#define PCA9698_CONFIG_PORT0 0x18
#define PCA9698_CONFIG_PORT1 0x19
#define PCA9698_CONFIG_PORT2 0x1A
#define PCA9698_CONFIG_PORT3 0x1B
#define PCA9698_CONFIG_PORT4 0x1C
#define PCA9698_CONFIG_PORT0_AUTO_INCREMENT 0x98
#define PCA9698_MASK_INTERUPT_PORT0 0x20
#define PCA9698_MASK_INTERUPT_PORT1 0x21
#define PCA9698_MASK_INTERUPT_PORT2 0x22
#define PCA9698_MASK_INTERUPT_PORT3 0x23
#define PCA9698_MASK_INTERUPT_PORT4 0x24
#define PCA9698_MASK_INTERUPT_PORT0_AUTO_INCREMENT 0xa0
#define PCA9698_MODE_REGISTER 0x2A`

Using defines, it will make the code more easy to debug.

**Comment by Justin-Pl** [comment]
I added them and some other defines. Will be in the next release. Perhaps today
