### ISSUE TITLE
Interrupt functionality

### ISSUE THREAD

**Issue by Thieuzor** [Justin-Pl/PCA9698#4]
I'm using 3 PCA9698s and wrote my own interrupt management in the main loop. It would be great to see this implemented in the library. There is an ESP32 used in my design thus testing it on different platforms is somewhat more difficult.

Using the SMBAlert function when even more IO-expanders are used is a better solution.

**Comment by Justin-Pl** [comment]
I made a function to activate normal interrupt line. SMBAlert is not supported yet. New release is published with all improvments. Please feel free to test and give feedback.
