### ISSUE TITLE
Option to read the output state of the IO expander at boot

### ISSUE THREAD

**Issue by Thieuzor** [Justin-Pl/PCA9698#5]
When rebooting, the state of the outputs are lost. An option to read the output state of the IO expander during init would prevent weird behaviours when for certain reason the main controller reboots.

**Comment by Justin-Pl** [comment]
If I get your issue right, I changed the begin functions so that all IOs will be configured as inputs and all output and input registers get cleared. Mode register will be configured as default if not changed in optional function argument. If I missunderstood something please tell me.
